version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: go-ecommerce-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopDev
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  redis:
    image: redis:7-alpine
    container_name: go-ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mysql_data:


