server:
  port: 8080
databases:
  - host: localhost
    port: 5432
    user: admin 
    password: admin
    dbname: shopDev
  - host: localhost
    port: 6379
    user: admin 
    password: admin
    dbname: userDev
security:
  jwt:
    key: abc123